// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmxwwfkrmsjyursybspx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRteHd3ZmtybXNqeXVyc3lic3B4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjIwMjAsImV4cCI6MjA2MzM5ODAyMH0.jVsffQ1-DYAX-bxYgf7V2n-BooHxi7OfM-x9c5tZeXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);